apiVersion: demo.anthos.com/v1
kind: Cluster
metadata:
  name: cluster-2
spec:
  compositionRef:
    name: cluster-gcp-gke  # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
  compositeDeletePolicy: Foreground
  parameters:
    location: "us-central1-c" # for AKS EKS us-east-1 is hard coded in the composition aws.eks.yaml
    clusterName: "cluster-2"
    nodeSize: medium  # Possible values small, medium, large
    minNodeCount: 2
    k8sVersion: "1.24"
    fleetProject: "111111" #GCP project number of fleet
    # Available GCP Regions for attached cluster API 
    #https://cloud.google.com/anthos/clusters/docs/multi-cloud/attached/eks/reference/supported-regions
    #Attached Cluster Pre-reqs https://cloud.google.com/anthos/clusters/docs/multi-cloud/attached/eks/reference/cluster-prerequisites
    anthosGCPRegion: us-east4 #us-east4 or us-west1
    adminUsers:
    - example@google.com
    #Azure Specific 
    resourceGroup: abc
