---
apiVersion: containerservice.azure.gke.cloud.google.com/v1beta1
kind: KubernetesCluster
metadata:
  annotations:
    crossplane.io/external-name: aks-cluster # name of cluster
  name: aks-cluster # name of cluster
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
        diskEncryptionSetId : ExistingDiskEncryptionSetResourceFullId # replace with existing disk encryption set id
    dnsPrefix: akscluster
    identity:
      - type: SystemAssigned
    location: "East US 2" #replace with region 
    resourceGroupName: ExistingResourceGroupName # replace with resource group
    kubernetesVersion: "1.27"
   
        
