#example of GKE on GCP with composition and adding it to a fleet
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-gcp-gke
  labels:
    crossplane.io/xrd: compositeclusters.demo.anthos.com
    provider: gcp
    cluster: gke
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeCluster
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: cluster
    base:
      apiVersion: container.gcp.gke.cloud.google.com/v1beta1
      kind: Cluster
      metadata:  
      spec:
        forProvider:
          initialNodeCount: 1
          location: us-central1-a
          minMasterVersion: 1.26
          removeDefaultNodePool: true
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.forProvider.minMasterVersion
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.masterVersion
      toFieldPath: status.version  
    - type: ToCompositeFieldPath
      fromFieldPath: spec.forProvider.location
      toFieldPath: status.region
  - name: nodepool
    base:
      apiVersion: container.gcp.gke.cloud.google.com/v1beta1
      kind: NodePool
      metadata:
        annotations:
      spec:
        forProvider:
          clusterSelector:
            matchControllerRef: true
          # location: us-central1-a
          nodeConfig:
            - machineType: e2-medium
              oauthScopes:
                - https://www.googleapis.com/auth/cloud-platform
             # nodeLocations: 
              #  - us-central1-a
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.nodeCount
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.nodeConfig[0].machineType
      transforms:
        - type: map
          map:
            small: e2-small
            medium: e2-medium
            large: e2-standard-2
  - name: fleetregistration
    base:
      apiVersion: gkehub.gcp.gke.cloud.google.com/v1beta1
      kind: Membership
      metadata:
        labels:
          testing.anthos/name: membership
        name: gke-from-config
      spec:
        forProvider:
          endpoint:
            - gkeCluster:
                - resourceLinkSelector:
                    matchLabels:
                      crossplane.io/claim-name: gke-with-3
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: metadata.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.endpoint[0].gkeCluster[0].resourceLinkSelector.matchLabels[crossplane.io/claim-name]
